// src/constants/sampleTracks.ts
//
// These are purely CLIENT-SIDE fallback tracks shown when the DB is empty
// or the API fetch fails.  They are never stored in MongoDB.
//
// They intentionally use the prefix "demo_" in their IDs so that:
//   • The route handler can detect them and return a clear 400 error
//   • The Admin Dashboard can hide the delete button for them
//   • page.tsx can show a banner prompting the admin to seed real tracks

import type { Track } from "@/types";

export const SAMPLE_TRACKS: Track[] = [
  // {
  //   id: "demo_t1",
  //   title: "Midnight Dreams",
  //   artist: "Luna Eclipse",
  //   album: "Cosmic Vibes",
  //   genre: ["Lo-Fi", "Chill"],
  //   duration: 213,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  //   cover: "https://picsum.photos/seed/nex1/400/400",
  //   featured: true,
  //   playCount: 1247,
  //   order: 1,
  //   isActive: true,
  // },
  // {
  //   id: "demo_t2",
  //   title: "Electric Pulse",
  //   artist: "Neon Circuits",
  //   album: "Digital Horizon",
  //   genre: ["Hype", "Electronic"],
  //   duration: 186,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  //   cover: "https://picsum.photos/seed/nex2/400/400",
  //   featured: true,
  //   playCount: 892,
  //   order: 2,
  //   isActive: true,
  // },
  // {
  //   id: "demo_t3",
  //   title: "Forest Walk",
  //   artist: "Acoustic Soul",
  //   album: "Nature's Call",
  //   genre: ["Acoustic", "Ambient"],
  //   duration: 241,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  //   cover: "https://picsum.photos/seed/nex3/400/400",
  //   featured: false,
  //   playCount: 634,
  //   order: 3,
  //   isActive: true,
  // },
  // {
  //   id: "demo_t4",
  //   title: "Jazz in the Rain",
  //   artist: "Miles & Friends",
  //   album: "Rainy Nights",
  //   genre: ["Jazz", "Chill"],
  //   duration: 198,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  //   cover: "https://picsum.photos/seed/nex4/400/400",
  //   featured: false,
  //   playCount: 445,
  //   order: 4,
  //   isActive: true,
  // },
  // {
  //   id: "demo_t5",
  //   title: "City Lights",
  //   artist: "Urban Groove",
  //   album: "Metropolitan",
  //   genre: ["Electronic", "Hype"],
  //   duration: 225,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  //   cover: "https://picsum.photos/seed/nex5/400/400",
  //   featured: true,
  //   playCount: 2103,
  //   order: 5,
  //   isActive: true,
  // },
  // {
  //   id: "demo_t6",
  //   title: "Serene Valley",
  //   artist: "Nature Beats",
  //   album: "Earthly Sounds",
  //   genre: ["Ambient", "Chill"],
  //   duration: 312,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  //   cover: "https://picsum.photos/seed/nex6/400/400",
  //   featured: false,
  //   playCount: 378,
  //   order: 6,
  //   isActive: true,
  // },
  // {
  //   id: "demo_t7",
  //   title: "Lo-Fi Study Session",
  //   artist: "ChillHop Master",
  //   album: "Study Beats Vol.2",
  //   genre: ["Lo-Fi", "Chill"],
  //   duration: 267,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
  //   cover: "https://picsum.photos/seed/nex7/400/400",
  //   featured: true,
  //   playCount: 3421,
  //   order: 7,
  //   isActive: true,
  // },
  // {
  //   id: "demo_t8",
  //   title: "Mountain Echo",
  //   artist: "Sky Voyager",
  //   album: "Above The Clouds",
  //   genre: ["Acoustic", "Ambient"],
  //   duration: 189,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  //   cover: "https://picsum.photos/seed/nex8/400/400",
  //   featured: false,
  //   playCount: 521,
  //   order: 8,
  //   isActive: true,
  // },
  // {
  //   id: "demo_t9",
  //   title: "Neon Nights",
  //   artist: "Synthwave Kid",
  //   album: "Retro Future",
  //   genre: ["Electronic", "Hype"],
  //   duration: 234,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
  //   cover: "https://picsum.photos/seed/nex9/400/400",
  //   featured: false,
  //   playCount: 987,
  //   order: 9,
  //   isActive: true,
  // },
  // {
  //   id: "demo_t10",
  //   title: "Coffee & Rain",
  //   artist: "Mellow Vibes",
  //   album: "Morning Rituals",
  //   genre: ["Lo-Fi", "Jazz"],
  //   duration: 178,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
  //   cover: "https://picsum.photos/seed/nex10/400/400",
  //   featured: false,
  //   playCount: 756,
  //   order: 10,
  //   isActive: true,
  // },
  // {
  //   id: "demo_t11",
  //   title: "Desert Highway",
  //   artist: "Road Tripper",
  //   album: "Open Roads",
  //   genre: ["Acoustic", "Hype"],
  //   duration: 256,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
  //   cover: "https://picsum.photos/seed/nex11/400/400",
  //   featured: false,
  //   playCount: 312,
  //   order: 11,
  //   isActive: true,
  // },
  // {
  //   id: "demo_t12",
  //   title: "Deep Space",
  //   artist: "Cosmos Explorer",
  //   album: "Interstellar",
  //   genre: ["Electronic", "Ambient"],
  //   duration: 298,
  //   src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
  //   cover: "https://picsum.photos/seed/nex12/400/400",
  //   featured: false,
  //   playCount: 189,
  //   order: 12,
  //   isActive: true,
  // },
];

/** True when a track is a client-side demo (never in MongoDB) */
export const isDemoTrack = (id: string) => id.startsWith("demo_");